# Generated by Django 5.0.4 on 2024-05-15 18:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_faculty_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='student_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.designation'),
        ),
        migrations.CreateModel(
            name='Known_Encoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty')], max_length=20)),
                ('encoding', models.BinaryField(max_length=1024)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.faculty')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
