# Generated by Django 5.0.4 on 2024-05-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_designation_student_image_alter_faculty_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='student_images/'),
        ),
    ]
