# Generated by Django 5.0.4 on 2024-05-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
