# Generated by Django 5.0.4 on 2024-05-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
