# Generated by Django 5.0.4 on 2024-05-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_attendance_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendee_type',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='faculty',
        ),
    ]
