# Generated by Django 5.0.4 on 2024-05-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_attendance_attendee_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='known_encoding',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='known_encoding',
            name='user_type',
        ),
    ]
